src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'Un utilisateur existe déjà avec ce nom d\'utilisateur.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 180,
        minMessage: 'Le nom d\'utilisateur doit faire au moins {{ limit }} caractères.',
        maxMessage: 'Le nom d\'utilisateur doit faire au maximum {{ limit }} caractères.',
    )]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\Length(
        min: 6,
        max: 4096,
        minMessage: 'Le mot de passe doit faire au moins {{ limit }} caractères.',
        maxMessage: 'Le mot de passe ne doit pas faire plus de {{ limit }} caractères.',
    )]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comment;

    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'likes')]
    private Collection $liked_articles;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $register_date = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Length(
        min: 1,
        max: 4096,
        minMessage: 'Le nom doit faire au moins {{ limit }} caractères.',
        maxMessage: 'Le nom ne doit pas faire plus de {{ limit }} caractères.',
    )]
    private ?string $about = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Article::class)]
    private Collection $wrote_articles;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Media::class)]
    private Collection $media;


    public function __construct(?string $username = null)
    {
        $this->username = $username;
        $this->comment = new ArrayCollection();
        $this->liked_articles = new ArrayCollection();
        $this->register_date = new \DateTime('now');
        $this->wrote_articles = new ArrayCollection();
        $this->media = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getLikedArticles(): Collection
    {
        return $this->liked_articles;
    }

    public function addLikedArticle(Article $likedArticle): self
    {
        if (!$this->liked_articles->contains($likedArticle)) {
            $this->liked_articles->add($likedArticle);
            $likedArticle->addLike($this);
        }

        return $this;
    }

    public function removeLikedArticle(Article $likedArticle): self
    {
        if ($this->liked_articles->removeElement($likedArticle)) {
            $likedArticle->removeLike($this);
        }

        return $this;
    }

    public function getRegisterDate(): ?\DateTimeInterface
    {
        return $this->register_date;
    }

    public function setRegisterDate(\DateTimeInterface $register_date): self
    {
        $this->register_date = $register_date;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): self
    {
        $this->about = $about;

        return $this;
    }

    public function __toString(): string
    {
        return $this->username;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getWroteArticles(): Collection
    {
        return $this->wrote_articles;
    }

    public function addWroteArticle(Article $wroteArticle): self
    {
        if (!$this->wrote_articles->contains($wroteArticle)) {
            $this->wrote_articles->add($wroteArticle);
            $wroteArticle->setAuthor($this);
        }

        return $this;
    }

    public function removeWroteArticle(Article $wroteArticle): self
    {
        if ($this->wrote_articles->removeElement($wroteArticle)) {
            // set the owning side to null (unless already changed)
            if ($wroteArticle->getAuthor() === $this) {
                $wroteArticle->setAuthor(null);
            }
        }

        return $this;
    }

    public static function loadValidatorMetadata(ClassMetadata $classMetadata)
    {
        $classMetadata->addPropertyConstraint('username', new Assert\NotBlank());
        $classMetadata->addPropertyConstraint('password', new Assert\NotBlank());
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media->add($medium);
            $medium->setAuthor($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getAuthor() === $this) {
                $medium->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\Type\RegistrationFormType;
use App\Form\Type\UpdateProfileType;
use App\Service\ArticleService;
use App\Service\OptionService;
use App\Service\UserService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class UserController extends AbstractController
{
    public function __construct(
        private OptionService  $optionService,
        private ArticleService $articleService,
    )
    {
    }

    #[Route('/user/register', name: 'app_register')]
    public function register(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $userCanRegister = $this->optionService->getValue('blog_allow_registration');
        if (!$userCanRegister) {
            return $this->redirectToRoute('app_home');
        }
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_home');
        }

        return $this->render('user/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route(path: '/user/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('app_home');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('user/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route('/user/{username}', name: 'user_profile')]
    public function index(?User $user): Response
    {
        if (!$user) {
            return $this->redirectToRoute('app_home');
        }
        $form = $this->createForm(UpdateProfileType::class, $user);
        return $this->render('user/index.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/ajax/profile', name: 'user_profile_update')]
    public function update(Request $request, EntityManagerInterface $entityManager, UserService $userService): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        if (!$user) {
            return $this->json([
                'code' => 'USER_NOT_AUTHENTICATED_FULLY',
                'message' => 'Vous devez être authentifié pour modifier votre profil',
            ], Response::HTTP_UNAUTHORIZED);
        }
        $form = $this->createForm(UpdateProfileType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if ($userService->getUserByUsername($form->get('username')->getData())) {
                if ($user !== $userService->getUserByUsername($form->get('username')->getData())) {
                    return $this->json([
                        'code' => 'USERNAME_ALREADY_EXISTS',
                        'message' => 'Ce nom d\'utilisateur est déjà utilisé',
                    ], Response::HTTP_BAD_REQUEST);
                }
            }
            $entityManager->persist($user);
            $entityManager->flush();
            return $this->json([
                'code' => 'PROFILE_UPDATED_SUCCESSFULLY',
                'message' => 'Votre profil a été mis à jour avec succès',
                'username' => $user->getUsername(),
                'about' => $user->getAbout(),
            ], Response::HTTP_OK);
        }
        return $this->json([
            'code' => 'PROFILE_UPDATE_FAILED',
            'message' => 'Une erreur est survenue lors de la mise à jour de votre profil',
        ], Response::HTTP_BAD_REQUEST);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <div class="hero is-fullheight form form-login">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns">
                    <div class="column is-6 is-offset-3">
                        <div class="card">
                            <div class="card-header" style="align-items: center">
                                <p class="card-header-title" id="username">
                                    @{{ user.username }}
                                </p>
                                {% if app.user == user %}
                                    <span class="icon mx-3" id="modify">
                                        <i class="fa fa-pencil"></i>
                                    </span>
                                {% endif %}
                            </div>
                            <div class="card-content content">
                                <blockquote class="blockquote" id="about">
                                    <p class="mb-0">
                                        {{ user.about }}
                                    </p>
                                </blockquote>
                                <div class="box">
                                    <div class="content">
                                        <p>
                                            {{ user.comment.count }} commentaires
                                        </p>
                                    </div>
                                </div>
                                <div class="box">
                                    <div class="content">
                                        <p>
                                            {% if user.likedArticles.count == 0 %}
                                                <span id="like_count">0</span> articles aimés
                                            {% else %}
                                                {% if user.likedArticles.count == 1 %}
                                                    <span id="like_count">1</span> article aimé
                                                {% else %}
                                                    <span id="like_count">{{ user.likedArticles.count }}</span> articles aimés
                                                {% endif %}
                                            {% endif %}
                                        </p>
                                        <table class="table">
                                            <tbody>
                                            {% for article in user.likedArticles %}
                                                <tr id="row_{{ article.id }}" class="liked_article">
                                                    <td>{{ article.title }}</td>
                                                    <td>
                                                        <a href="{{ path('article_show', {'slug': article.slug}) }}">
                                                            <i class="fa fa-eye see_liked"></i>
                                                        </a>
                                                    </td>
                                                    {% if user == app.user %}
                                                        <td>
                                                            <i class="fa fa-minus-circle remove_like"
                                                               data-article-id="{{ article.id }}"></i>
                                                        </td>
                                                    {% endif %}
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="modal-profile">
        <div class="modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title" id="modal-title">Mon profil</p>
                <button class="delete" aria-label="close" id="modal-close"></button>
            </header>
            <section class="modal-card-body">
                {{ form_start(form, {'attr': {'id': 'form-profile'}}) }}
                <div class="field">
                    {{ form_label(form.username) }}
                    <div class="control">
                        {{ form_widget(form.username) }}
                    </div>
                </div>
                <div class="field">
                    {{ form_label(form.about) }}
                    <div class="control">
                        {{ form_widget(form.about) }}
                    </div>
                </div>
                <div class="notification" id="notification">
                    <p class="has-text-centered">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw" id="spinner"></i>
                        <span id="message"></span>
                    </p>
                </div>
                <div class="field is-grouped py-3 is-flex is-justify-content-space-between is-align-content-end">
                    <div class="control">
                        {{ form_widget(form.submit) }}
                        {{ form_end(form) }}
                    </div>
                    <div class="control">
                        <a class="button is-warning" id="modal-cancel">Annuler</a>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}
{% block bodyclass %}second{% endblock %}
{% block body %}
    <div class="hero is-fullheight form form-login">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns is-multiline">
                    <div class="column is-8 is-offset-2 register">
                        <div class="columns box form-box">
                            <div class="column left is-flex is-flex-direction-column is-justify-content-center">
                                <div class="is-flex is-flex-direction-column is-justify-content-center pr-5 leftbox"
                                     style="height: 66%">
                                    <h1 class="title is-1">{{ options['blog_title'] }}</h1>
                                    <h2 class="subtitle colored is-4">Formulaire de connexion</h2>
                                    <p>Si vous êtes passionné par la technologie et le développement web, alors
                                        Technologin est le blog pour vous ! Vous y trouverez des nouvelles, des conseils
                                        et des tutoriels sur tout ce qui touche à la technologie et au web, afin que
                                        vous pouvez rester à jour et acquérir de nouvelles compétences.</p>
                                </div>
                            </div>
                            <div class="column right has-text-centered">
                                <h1 class="title is-4">Se connecter</h1>
                                <p class="description">
                                    Connectez-vous à votre compte pour accéder à votre espace personnel.
                                </p>
                                <br>
                                <form method="post">
                                    {% if error %}
                                        <div class="notification is-danger">
                                            {{ error.messageKey|trans(error.messageData, 'security') }}
                                        </div>
                                    {% endif %}
                                    <div class="field">
                                        <label class="label" for="inputUsername">Nom d'utilisateur</label>
                                        <div class="control">
                                            <input type="text" class="input effect-1" value="{{ last_username }}"
                                                   name="_username" id="inputUsername" autocomplete="username" required
                                                   autofocus placeholder="John Doe">
                                            <span class="focus-border"></span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <label for="inputPassword" class="label">Mot de passe</label>
                                        <div class="control">
                                            <input type="password" class="input effect-1" name="_password" id="inputPassword"
                                                   autocomplete="current-password" required placeholder="******">
                                            <span class="focus-border"></span>
                                        </div>
                                    </div>
                                    <input type="hidden" name="_csrf_token"
                                           value="{{ csrf_token('authenticate') }}"
                                    >
                                    <button class="button is-block is-button  is-fullwidth mt-5">
                                        Connexion
                                        <i class="fa fa-sign-in" aria-hidden="true"></i>
                                    </button>
                                    <br>
                                    <small>
                                        <em>
                                            Vous n'avez pas de compte ? <a href="{{ path('app_register') }}">Inscrivez-vous</a>
                                        </em>
                                    </small>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}
{% block bodyclass %}second{% endblock %}
{% block body %}
    <div class="hero is-fullheight has-shadow has-black-gradient form form-register">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns is-multiline">
                    <div class="column is-8 is-offset-2 register">
                        <div class="columns box form-box">
                            <div class="column left is-flex is-flex-direction-column is-justify-content-center">
                                <div class="lefbox is-flex is-flex-direction-column is-justify-content-center pr-5 leftbox"
                                     style="height: 66%">

                                    <h1 class="title is-1">{{ options['blog_title'] }}</h1>
                                    <h2 class="subtitle colored is-4">Actus, conseils et tutos sur la technologie et le
                                        développement web.</h2>
                                    <p>Si vous êtes passionné par la technologie et le développement web, alors
                                        Technologin est le blog pour vous ! Vous y trouverez des nouvelles, des conseils
                                        et des tutoriels sur tout ce qui touche à la technologie et au web, afin que
                                        vous pouvez rester à jour et acquérir de nouvelles compétences.</p>
                                </div>
                            </div>
                            <div class="column right has-text-centered">
                                <h1 class="title is-4">S'inscrire</h1>
                                <p class="description">Créez votre compte pour accéder à toutes les fonctionnalités de
                                    Technologin.</p>
                                <br>
                                {{ form_start(registrationForm) }}
                                <div class="field">
                                    {{ form_label(registrationForm.username) }}
                                    <div class="control">
                                        {{ form_widget(registrationForm.username) }}
                                        <span class="focus-border"></span>
                                    </div>
                                    <div class="form-error">
                                        {{ form_errors(registrationForm.username) }}
                                    </div>
                                </div>

                                <div class="field">
                                    {{ form_label(registrationForm.plainPassword.password) }}
                                    <div class="control">
                                        {{ form_widget(registrationForm.plainPassword.password) }}
                                        <span class="focus-border"></span>
                                    </div>
                                    {% if registrationForm.plainPassword.password.vars['errors']|length > 0 %}
                                        {% for error in registrationForm.plainPassword.password.vars['errors'] %}
                                            <p class="help is-danger">
                                                {{ error.message }}
                                            </p>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="field">
                                    {{ form_label(registrationForm.plainPassword.confirm) }}
                                    <div class="control">
                                        {{ form_widget(registrationForm.plainPassword.confirm) }}
                                        <span class="focus-border"></span>
                                    </div>
                                </div>

                                <button class="button is-block is-button is-fullwidth"
                                        data-dashlane-rid="27f0e5d90fd4084c" data-form-type=""
                                        data-dashlane-label="true">
                                    Inscription
                                    <i class="fa fa-user-plus"></i>
                                </button>
                                <br>
                                <small><em>Vous avez déjà un compte ? <a
                                                href="{{ path('app_login') }}">Connectez-vous</a>.</em></small>
                                {{ form_end(registrationForm) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}